/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LeczenieRouteImport } from './routes/leczenie'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as GabinetRouteImport } from './routes/gabinet'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LeczenieRoute = LeczenieRouteImport.update({
  id: '/leczenie',
  path: '/leczenie',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const GabinetRoute = GabinetRouteImport.update({
  id: '/gabinet',
  path: '/gabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gabinet': typeof GabinetRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/leczenie': typeof LeczenieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gabinet': typeof GabinetRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/leczenie': typeof LeczenieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gabinet': typeof GabinetRoute
  '/galeria': typeof GaleriaRoute
  '/kontakt': typeof KontaktRoute
  '/leczenie': typeof LeczenieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gabinet'
    | '/galeria'
    | '/kontakt'
    | '/leczenie'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gabinet' | '/galeria' | '/kontakt' | '/leczenie' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/gabinet'
    | '/galeria'
    | '/kontakt'
    | '/leczenie'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GabinetRoute: typeof GabinetRoute
  GaleriaRoute: typeof GaleriaRoute
  KontaktRoute: typeof KontaktRoute
  LeczenieRoute: typeof LeczenieRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leczenie': {
      id: '/leczenie'
      path: '/leczenie'
      fullPath: '/leczenie'
      preLoaderRoute: typeof LeczenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gabinet': {
      id: '/gabinet'
      path: '/gabinet'
      fullPath: '/gabinet'
      preLoaderRoute: typeof GabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GabinetRoute: GabinetRoute,
  GaleriaRoute: GaleriaRoute,
  KontaktRoute: KontaktRoute,
  LeczenieRoute: LeczenieRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
